services:
  mssqldata:
    build: .
    container_name: mssqldata
    environment:
      - SA_PASSWORD=Agenzia2022Pass
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./mssqlagenzia:/var/opt/mssql/data
    expose:
      - "1433"
