version: "3.9"
services:
  rabbitmq_agenzia:
    build: .
    container_name: rabbitmq_agenzia
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_agenzia:/var/lib/rabbitmq
