version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database_pg
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: api
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata: # default is local (driver:local)